In [2]:
!pip install theano

     ---------------------------------------- 2.8/2.8 MB 111.6 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for theano: filename=Theano-1.0.5-py3-none-any.whl size=2668125 sha256=dad609206668a6598f521f42ab5194df4e882ef5e412ddf90df1b28f9e47ec07
  Stored in directory: c:\users\tingil\appdata\local\pip\cache\wheels\84\cb\19\235b5b10d89b4621f685112f8762681570a9fa14dc1ce904d9
Successfully built theano


In [62]:
!pip install opencv-python
!pip install opencv-python-headless

     -------------------------------------- 35.3/35.3 MB 963.7 kB/s eta 0:00:00


In [64]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from keras import layers, models, datasets
from tensorflow.keras.models import Sequential
import cv2
import os
import PIL

ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (C:\Users\TINGIL\anaconda3\lib\site-packages\cv2\cv2.cp38-win_amd64.pyd)

In [2]:
(X_train, y_train), (X_test, y_test)=tf.keras.datasets.cifar10.load_data()

In [3]:
X_train.shape

(50000, 32, 32, 3)

In [4]:
X_train[0][0]

array([[ 59,  62,  63],
       [ 43,  46,  45],
       [ 50,  48,  43],
       [ 68,  54,  42],
       [ 98,  73,  52],
       [119,  91,  63],
       [139, 107,  75],
       [145, 110,  80],
       [149, 117,  89],
       [149, 120,  93],
       [131, 103,  77],
       [125,  99,  76],
       [142, 115,  91],
       [144, 112,  86],
       [137, 105,  79],
       [129,  97,  71],
       [137, 106,  79],
       [134, 106,  76],
       [124,  97,  64],
       [139, 113,  78],
       [139, 112,  75],
       [133, 105,  69],
       [136, 105,  74],
       [139, 108,  77],
       [152, 120,  89],
       [163, 131, 100],
       [168, 136, 108],
       [159, 129, 102],
       [158, 130, 104],
       [158, 132, 108],
       [152, 125, 102],
       [148, 124, 103]], dtype=uint8)

In [5]:
def plot_sample(index):
    plt.figure(figsize=(10,10))
    plt.imshow(X_train[1])

In [6]:
y_test[6][0]

1

In [7]:
plot_sample(1)

In [8]:
X_train=X_train/255
y_train=y_train/255

In [9]:
y_train.shape

(50000, 1)

In [10]:
y_train_categorical = keras.utils.to_categorical(y_train, num_classes=10, dtype="float")

In [11]:
y_train_categorical

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [12]:
y_test_categorical = keras.utils.to_categorical(y_test, num_classes=10, dtype="float")

In [13]:
y_test_categorical

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [14]:
model= keras.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)),
    keras.layers.Dense(3000, activation="relu"),
    keras.layers.Dense(1000, activation="relu"),
    keras.layers.Dense(10, activation="sigmoid")
])
model.compile(
    optimizer="SGD",
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(X_train, y_train_categorical, epochs=1)

1563/1563 [==============================] - 157s 99ms/step - loss: 0.0027 - accuracy: 0.9999


In [16]:
model.evaluate(X_test, y_test_categorical)

313/313 [==============================] - 11s 34ms/step - loss: 3950.7180 - accuracy: 0.1000


[3950.718017578125, 0.10000000149011612]

In [28]:
np.argmax(model.predict(X_test)[1])

0

In [29]:
y_test[0]

array([3], dtype=uint8)

In [34]:
model.evaluate(X_test, y_test_categorical)

313/313 [==============================] - 11s 35ms/step - loss: 3950.7180 - accuracy: 0.1000 4s - loss: 3970.4458 -


[3950.718017578125, 0.10000000149011612]

In [43]:
cnn = model.Sequential([
    
    layers.Conv2D(filters=32, kernels_size=(3,3), activation='relu',input_shape=(32,32,3)),
    layers.MaxPooling2D((2,2)),
    
    layers.Flatten(),
    layers.Dense(64, activation="relu"),
    layers.Dense(10, activation="softmax"),
])
    
cnn.compile(
        optimizer="SGD",
        loss='categorical_crossentropy',
        metrics=['accuracy']
             )
    
cnn.fit(X_train, y_train_categorical, epochs=1)
    

AttributeError: 'Sequential' object has no attribute 'Sequential'

In [50]:
!pip install opencv--python 